# Parameters
/glg4debug/glg4param omit_muon_processes 1.0
/glg4debug/glg4param omit_hadronic_processes 1.0
/glg4debug/glg4param omit_neutron_hp 1.0

/rat/db/set MC thin_factor 3.5
/rat/db/set GEO[scint] material "lightwater_sno"

/run/initialize

/rat/proc frontend
/rat/proc trigger
/rat/proc eventbuilder
/rat/proc count
/rat/procset update 10
/rat/proc calibratePMT
/rat/proc outroot
/rat/procset file "/home/coulter/rat-tools/FitCoordination/DirectionPDF/PDF_10MeV_5k.root"

# Generator

/generator/add combo gun:point
/generator/vtx/set e- 0 0 0 10.0
/generator/pos/set 0.0 0.0 0.0
/generator/rate/set 1

/run/beamOn 5000

exit
