/glg4debug/glg4param omit_muon_processes  1.0
/glg4debug/glg4param omit_hadronic_processes  1.0

/run/initialize

# BEGIN EVENT LOOP
/rat/proc frontend
/rat/proc trigger
/rat/proc eventbuilder
/rat/proc calibratePMT

/rat/proc count
/rat/procset update 100

# Add Fitter(s) here then rename file

/rat/proc outroot
/rat/procset file "${OutFileName}"

# END EVENT LOOP
${Generator}
/generator/rate/set 1

/run/beamOn 500
exit
