/PhysicsList/OmitMuonicProcesses true
/PhysicsList/OmitHadronicProcesses true

/run/initialize

# BEGIN EVENT LOOP
/rat/proc frontend
/rat/proc trigger
/rat/proc eventbuilder
/rat/proc calibratePMT

/rat/proc count
/rat/procset update 100

# Add Fitter(s) here then rename file

/rat/proc outroot
/rat/procset file "${OutFileName}"

# END EVENT LOOP
${Generator}
/generator/rate/set 1

/rat/run/start 500
exit
