/*-----------------------------------------------------------------------
/// This program merges all the simple root-files created with the user processor for FitLike input.
/// Specify the list of input files in files_pos.txt, output written to FitLikePDFntuple.root (these
/// default names can be changed on the command line). 
/// The files can be created with the macro and script files generated by the 
/// write_scriptcmd_likeposPDFs.perl perl script.

/// To run
/// To run, open root, and type:
/// > .L MergeNtuples.C
/// > MergeNtuples()
-----------------------------------------------------------------------*/

// Root includes
#include "TROOT.h"
#include "TFile.h"
#include "TNtuple.h"

// C++ includes
#include <stdlib.h>
#include <stdio.h>
#include <iostream>
#include <fstream>
using std::cout;
using std::endl;

void MergeNtuples(char* fileList = "files_pos.txt", char *fileOutName = "FitLikePDFNtuple.root")
{
	// list of input files
	ifstream fin;
	fin.open(fileList);

	// filenames
	char Cname[100];
	// rootfiles
	TFile *fileIn;
							  
	// Set up the output file
	TFile *fileOut = TFile::Open(fileOutName, "RECREATE");
	TNtuple *flntp = new TNtuple("flntp","PDF entries ntuple","nV:nQ:nA:tres");
	cout << "opened file " << fileOutName << " for writing " <<  endl;
	
	
	fin >> Cname;
	while(fin.good()){
		fileIn = new TFile(Cname);
		if(!fileIn){
			// problem opening input file
			cout << "Problem with file " << Cname << " - exiting now. " << endl;
			return;
		}
		// Access the tree (always called mytree)
		TNtuple *tntp = (TNtuple*)fileIn->Get("PDFntuple");
		if(!tntp){
			// problem opening input file
			cout << "Problem accessing ntuple in file " << Cname << " - exiting now. " << endl;
			return;
		}
		int nen = tntp->GetEntries();
		cout << Cname << " has " << nen << " entries " << endl;
		for(int i=0;i<nen;++i){
			// loop through entries
			tntp->GetEntry(i);
			float *vals = tntp->GetArgs();
			flntp->Fill(vals);
		}		
		// Now open the next file
		fin >> Cname;
	}		
    fileOut->cd();
	flntp->SetName("PDFntuple");
    flntp->Write();
    fileOut->Close();
				  
}
