# In this file the source is at 0.0 ${SourcePos} 0.0

# Parameters
/glg4debug/glg4param omit_muon_processes 1.0
/glg4debug/glg4param omit_hadronic_processes 1.0
/glg4debug/glg4param omit_neutron_hp 1.0

/rat/db/set DETECTOR geo_file "${GeoFile}"
/rat/db/set GEO[scint] material "${ScintMaterial}"

/rat/db/set OPTICS[${ScintMaterial}] SCINTWAVEFORM_value1 [ -0.0d, ]
/rat/db/set OPTICS[${ScintMaterial}] SCINTWAVEFORM_value2 [ 1.0d, ]

/run/initialize

/rat/proc frontend
/rat/proc trigger
/rat/proc eventbuilder
/rat/proc count
/rat/procset update 100
/rat/proc calibratePMT
/rat/proc outroot
/rat/procset file "P${SourcePos}.root"

# Generator

/generator/add combo gun:point
/generator/vtx/set ${Particle} 0 0 0 3.0

/generator/pos/set 0.0 ${SourcePos} 0.0
/generator/rate/set 1

/rat/run/start 500

exit
