/PhysicsList/OmitMuonicProcesses true
${OmitHadrons}
/rat/db/set DETECTOR geo_file "${GeoFile}"
/rat/db/set GEO[scint] material "${ScintMaterial}"
${PulseLengthTimeConstant}
${PulseLengthRatio}

/run/initialize

/rat/proc frontend
/rat/proc trigger
/rat/proc eventbuilder
/rat/proc calibratePMT
/rat/proc scintFitter
/rat/proc outroot
/rat/procset file "${OutFileName}"

/generator/add combo decay0:fill:uniform
${Generator}
/generator/pos/set 0 0 0
/generator/rate/set 1

/rat/run/start 5
exit
